# Název této automatizace
name: Deploy to Firebase Hosting on main push

# Kdy se má spustit: při nahrání (push) na větev 'main'
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DARKY_RODINA }}'
          channelId: live
          projectId: darky-rodina
